### ISSUE TITLE
Problem with updating  pdp.properties 

### ISSUE THREAD

**Issue by vasmarg** [authzforce/server#10]
When I try updating pdp.properties file via PUT request using xml

 `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pdpPropertiesUpdate xmlns="http://authzforce.github.io/rest-api-model/xmlns/authz/5">
<rootPolicyRefExpression>valid_policySet_id</rootPolicyRefExpression>
</pdpPropertiesUpdate>` 

It return Internal server error with message:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error xmlns="http://authzforce.github.io/rest-api-model/xmlns/authz/5"><message>Internal Server error. Retry later or contact the administrator.</message></error>`

Is anyone else experiencing this issue. Any help would be appreciated

**Comment by cdanger** [comment]
Please post here the server error log produced in `/var/log/tomcat7/authzforce-ce/error.log` when you do this request.

**Comment by vasmarg** [comment]
`2016-12-23 14:02:40,955|ERROR|http-bio-8081-exec-9|org.ow2.authzforce.webapp.ErrorHandlerInterceptor:77|Fatal CXF service error|
org.apache.cxf.interceptor.Fault: null
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:163) ~[cxf-core-3.1.0.jar:3.1.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:129) ~[cxf-core-3.1.0.jar:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200) ~[cxf-rt-frontend-jaxrs-3.1.0.jar:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:271) ~[cxf-rt-frontend-jaxrs-3.1.0.jar:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:271) ~[cxf-rt-frontend-jaxrs-3.1.0.jar:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:271) ~[cxf-rt-frontend-jaxrs-3.1.0.jar:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99) ~[cxf-rt-frontend-jaxrs-3.1.0.jar:3.1.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.1.0.jar:3.1.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.1.0.jar:3.1.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[cxf-core-3.1.0.jar:3.1.0]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.1.0.jar:3.1.0]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251) [cxf-rt-transports-http-3.1.0.jar:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.1.0.jar:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.1.0.jar:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.1.0.jar:3.1.0]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171) [cxf-rt-transports-http-3.1.0.jar:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293) [cxf-rt-transports-http-3.1.0.jar:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPut(AbstractHTTPServlet.java:229) [cxf-rt-transports-http-3.1.0.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:649) [tomcat-servlet-api-3.0.jar:na]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268) [cxf-rt-transports-http-3.1.0.jar:3.1.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.ow2.authzforce.webapp.ExceptionFilter.doFilter(ExceptionFilter.java:87) [ExceptionFilter.class:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [tomcat-catalina-7.0.52.jar:7.0.52]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-coyote-7.0.52.jar:7.0.52]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) [tomcat-coyote-7.0.52.jar:7.0.52]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313) [tomcat-coyote-7.0.52.jar:7.0.52]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]
Caused by: java.lang.NullPointerException: null
	at org.ow2.authzforce.core.pdp.impl.func.ImmutableFunctionRegistry.getFunction(ImmutableFunctionRegistry.java:97) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.expression.ExpressionFactoryImpl.getFunction(ExpressionFactoryImpl.java:302) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.expression.ApplyExpression.getInstance(ApplyExpression.java:145) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.expression.ExpressionFactoryImpl.getInstance(ExpressionFactoryImpl.java:317) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.expression.ApplyExpression.getInstance(ApplyExpression.java:109) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.expression.ExpressionFactoryImpl.getInstance(ExpressionFactoryImpl.java:317) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.rule.ConditionEvaluator.<init>(ConditionEvaluator.java:76) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.rule.RuleEvaluator.<init>(RuleEvaluator.java:385) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators.getInstance(PolicyEvaluators.java:1811) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators$StaticPolicySetElementEvaluatorFactory.getChildPolicyEvaluator(PolicyEvaluators.java:2095) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators$StaticPolicySetElementEvaluatorFactory.getChildPolicyEvaluator(PolicyEvaluators.java:2072) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators.getInstanceGeneric(PolicyEvaluators.java:2402) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators.getInstanceStatic(PolicyEvaluators.java:2524) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileDAORefPolicyProviderModule$PolicyEvaluatorSupplier.get(FlatFileDAORefPolicyProviderModule.java:239) ~[authzforce-ce-pap-dao-flat-file-6.1.0.jar:na]
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileDAORefPolicyProviderModule$PolicyEvaluatorSupplier.access$600(FlatFileDAORefPolicyProviderModule.java:188) ~[authzforce-ce-pap-dao-flat-file-6.1.0.jar:na]
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileDAORefPolicyProviderModule.get(FlatFileDAORefPolicyProviderModule.java:374) ~[authzforce-ce-pap-dao-flat-file-6.1.0.jar:na]
	at org.ow2.authzforce.core.pdp.api.policy.BaseStaticRefPolicyProvider.get(BaseStaticRefPolicyProvider.java:131) ~[authzforce-ce-core-pdp-api-7.1.1.jar:na]
	at org.ow2.authzforce.core.pdp.impl.policy.CoreRefBasedRootPolicyProviderModule.<init>(CoreRefBasedRootPolicyProviderModule.java:135) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.policy.CoreRefBasedRootPolicyProviderModule$Factory.getInstance(CoreRefBasedRootPolicyProviderModule.java:77) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.policy.CoreRefBasedRootPolicyProviderModule$Factory.getInstance(CoreRefBasedRootPolicyProviderModule.java:57) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.policy.RootPolicyEvaluators$Base.<init>(RootPolicyEvaluators.java:171) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.PDPImpl.<init>(PDPImpl.java:372) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.core.pdp.impl.PdpConfigurationParser.getPDP(PdpConfigurationParser.java:458) ~[authzforce-ce-core-5.0.2.jar:na]
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDAO$FileBasedDomainDAOImpl.reloadPDP(FlatFileBasedDomainsDAO.java:878) ~[authzforce-ce-pap-dao-flat-file-6.1.0.jar:na]
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDAO$FileBasedDomainDAOImpl.setOtherPdpProperties(FlatFileBasedDomainsDAO.java:1505) ~[authzforce-ce-pap-dao-flat-file-6.1.0.jar:na]
	at org.ow2.authzforce.rest.service.jaxrs.DomainResourceImpl.updateOtherPdpProperties(DomainResourceImpl.java:604) ~[authzforce-ce-server-rest-service-5.4.1.jar:na]
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_101]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_101]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181) ~[cxf-core-3.1.0.jar:3.1.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97) ~[cxf-core-3.1.0.jar:3.1.0]
	... 37 common frames omitted`

**Comment by vasmarg** [comment]
If I use other policySet sometimes it works

**Comment by cdanger** [comment]
This may be caused by an invalid PolicySet. In this case, I suspect the function used in one of the Apply expressions is not valid/supported. This is a bug indeed, since it should return a 40X error code instead of 500. 
**Could you attach here a file containing the PolicySet that you are not able to use in `<rootPolicyRefExpression>` because of this error?**  
This will help us reproduce the bug and give you a workaround if possible, while waiting for a bugfix.

**Comment by vasmarg** [comment]
Thank you for your reply. I found the issue: in Apply i was using functionId urn:oasis:names:tc:xacml:1.0:function:any-of
changed it to: 
urn:oasis:names:tc:xacml:3.0:function:any-of
worked fine. 

( Where can I find all the supported/unsupported functionIds, CombingAlgorithms etc. ? Couldn't find it in the documentation )

**Comment by cdanger** [comment]
Glad you fixed it. I created bug #11 to fix the confusing Internal Server Error.
You can find the list of supported features (functions, algorithms, datatypes...) in the **Features** section of the [README](https://github.com/authzforce/server/tree/master).

**Comment by vasmarg** [comment]
Thanks!

**Comment by cdanger** [comment]
Marked as duplicate of #11
