### ISSUE TITLE
Error while starting-up the authzforce ce server

### ISSUE THREAD

**Issue by amemon** [authzforce/server#16]
Hi,

I am trying to startup the authzforce server. But before that, I have built the v5.4.1 distribution with maven and configured my tomcat 8.0.35 (and openjdk 8) installation (that is placing the context.xml file to $catalina.base/conf/Catalina/localhost/authzforce-ce.xml). Now, when I start the tomcat server, following error is occurred under the catalina.out file.

27-May-2017 16:06:21.629 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor /home/user/apache-tomcat-8.0.35/conf/Catalina/localhost/authzforce-ce.xml
27-May-2017 16:06:27.162 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
27-May-2017 16:06:29.069 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
27-May-2017 16:06:29.073 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/authzforce-ce] startup failed due to previous errors
27-May-2017 16:06:29.089 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor /home/user/apache-tomcat-8.0.35/conf/Catalina/localhost/authzforce-ce.xml has finished in 7,460 ms

and under the error.log file:

2017-05-27 16:06:29,066|ERROR|localhost-startStop-1|org.springframework.web.context.ContextLoader:319|Context initialization failed|
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tazService': Invocation of init method failed; nested exception is org.apache.cxf.service.factory.ServiceConstructionException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1488) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:626) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932) ~[spring-context-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479) ~[spring-context-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389) ~[spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294) ~[spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112) [spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4813) [catalina.jar:8.0.35]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5272) [catalina.jar:8.0.35]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [catalina.jar:8.0.35]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.35]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.35]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.35]
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:587) [catalina.jar:8.0.35]
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1798) [catalina.jar:8.0.35]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: null
        at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:219) ~[cxf-rt-frontend-jaxrs-3.1.0.jar:3.1.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1614) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1555) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1485) ~[spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
        ... 25 common frames omitted
Caused by: java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_112]
        at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1084) ~[na:1.8.0_112]
        at org.apache.cxf.jaxrs.AbstractJAXRSFactoryBean.createEndpoint(AbstractJAXRSFactoryBean.java:223) ~[cxf-rt-frontend-jaxrs-3.1.0.jar:3.1.0]
        at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:165) ~[cxf-rt-frontend-jaxrs-3.1.0.jar:3.1.0]
        ... 32 common frames omitted

Any help would be appreciated.

Thanks,
Shiraz

**Comment by cdanger** [comment]
Unfortunately, v5.4.1 is not compatible with Tomcat8/JDK 8. See [the install guide](http://authzforce-ce-fiware.readthedocs.io/en/release-5.4.1d/InstallationAndAdministrationGuide.html#system-requirements) for more info. You should either downgrade to Tomcat7/JDK 7 if you want to stick with AuthzForce v5.4.1, or upgrade to the latest version of AuthzForce on our [OW2 Gitlab](https://gitlab.ow2.org/authzforce/server) repo, currently 7.0.0, that is compatible with Tomcat8/JDK 8. We may re-synchronize with Github later. Meanwhile, on the [release-7.0.0 page](https://gitlab.ow2.org/authzforce/server/tags/release-7.0.0) there, you can find the link to the debian package (for Debian/Ubuntu) or tar.gz (for other Linux distros) (hosted on Maven Central) for this release (and you have the release tag obviously if you want re-build from source). Although the documentation is not released yet, but most of the doc of v5.4.1 still applies (except System Requirements for instance). You may check the [release notes](https://gitlab.ow2.org/authzforce/server/blob/develop/CHANGELOG.md#700) for more info on changes between 5.4.1 and 7.0.0.

**Comment by amemon** [comment]
thanks @cdanger, I have used the gitlab repo to build v7.0.0 and was able to test the REST PAP api. One more question, is it possible to perform operations on policies and domains via WebUI (apart from REST interface)?

**Comment by hargathor** [comment]
Unfortunately AuthzForce does not have any UI at the moment. Operations on policies and domains can only be done using the REST API

**Comment by cdanger** [comment]
As @hargathor said, AuthzForce itself does not provide any UI. However, the REST API supports JSON so you can leverage that to develop your own Javascript-based WebUI. There is also another option based on an open source identity & access management solution developed by one of our partners (with limitations). 

For assigning domains/policysets, you could use the user-role or user-group assignment features of your identity manager (a good one has those features usually). Then you need a PEP (e.g. reverse proxy or CXF interceptor) to protect AuthzForce Server's REST API, that is able to intercept REST API calls and extract URL/path, method, header, etc. esp. the header giving the user role/group info (possibly derived from OAuth/SAML token), then pass the info to a PDP (e.g. in a special "admin" AuthzForce domain or an embedded AuthzForce Core PDP if Java-compatible). This is something we did in collaborative projects with partners that provide an IdM and PEP. Also one of tests in Authzforce server codes uses SAML to get roles for authorization. The hard part is to have the UI that works with AuthzForce REST API and is able to forward the OAuth (or SAML) token to the PEP protecting the API. And that, again, AuthzForce doesn't provide. 

Anyway, let's not mix all issues in the same place, since they are not related to the original issue title, and these are not simple issues, there is much to be said. They deserve their own page. 
So @amemon, **if you want a more complete answer, could you create one (or more) Github issue(s) specifically for these new questions, and link them from here?** Thanks.

**Comment by amemon** [comment]
Hi @cdanger and @hargathor, 
Thanks for your replies. I have created a new issue for more complete answer.
Shiraz
