### ISSUE TITLE
org.ow2.authzforce.domains.xacmlJsonSchemaRelativePath has no effect

### ISSUE THREAD

**Issue by securedimensions** [authzforce/server#70]
# Software version (AuthzForce Core)
21.2.0
# Platform JRE
11
# Platform OS
MAC
# Error stack trace or logs (if any)
The `Request.schema.json` seems not to get loaded from the location specified in the `authzforce-ce.xml` context deployment.
When submitting a JSON request with additional attribute `SRS`, the request is still validated against the schema loaded from `classpath` and not from the configured location.
````
2022-12-01 16:09:36,761|DEBUG|http-nio-8080-exec-2|org.apache.cxf.service.invoker.AbstractInvoker:175|Invoking method public abstract org.json.JSONObject org.ow2.authzforce.rest.api.jaxrs.PdpResource.requestPolicyDecisionXacmlJson(org.json.JSONObject) on object org.ow2.authzforce.rest.service.jaxrs.DomainResourceImpl@259f6a82 with params [{"Request":{"CombinedDecision":false,"Category":[{"CategoryId":"urn:oasis:names:tc:xacml:1.0:subject-category:access-subject","Attribute":[{"SRS":"EPSG:4326","AttributeId":"subject-location","Value":"POINT (10 1)","DataType":"urn:ogc:def:dataType:geoxacml:3.0:geometry","IncludeInResult":false}]}],"ReturnPolicyIdList":false}}].|
2022-12-01 16:10:28,510|DEBUG|http-nio-8080-exec-2|org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor:203|{
    "schemaLocation": "classpath://org/ow2/authzforce/xacml/json/model/common-std.schema.json#/definitions/AttributeType",
    "pointerToViolation": "#/Request/Category/0/Attribute/0",
    "causingExceptions": [],
    "keyword": "additionalProperties",
    "message": "extraneous key [SRS] is not permitted"
}|
2022-12-01 16:10:28,512|INFO |http-nio-8080-exec-2|org.ow2.authzforce.core.pdp.api.io.BasePdpEngineAdapter:149|Invalid or unsupported input XACML Request syntax|
org.ow2.authzforce.core.pdp.api.IndeterminateEvaluationException: Invalid Request
    at org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor.process(BaseXacmlJsonRequestPreprocessor.java:204)
    at org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor.process(BaseXacmlJsonRequestPreprocessor.java:47)
    at org.ow2.authzforce.core.pdp.api.io.BasePdpEngineAdapter.evaluate(BasePdpEngineAdapter.java:145)
    at org.ow2.authzforce.core.pdp.api.io.BasePdpEngineAdapter.evaluate(BasePdpEngineAdapter.java:193)
    at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao$PdpBundle.evaluate(FlatFileBasedDomainsDao.java:563)
    at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao$FileBasedDomainDaoImpl.evaluatePolicyDecision(FlatFileBasedDomainsDao.java:2605)
    at org.ow2.authzforce.rest.service.jaxrs.DomainResourceImpl.requestPolicyDecisionXacmlJson(DomainResourceImpl.java:270)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:578)
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:286)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:286)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:709)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
    at org.ow2.authzforce.webapp.ExceptionFilter.doFilter(ExceptionFilter.java:64)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:356)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:870)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1762)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
    at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.everit.json.schema.ValidationException: #/Request/Category/0/Attribute/0: extraneous key [SRS] is not permitted
    at org.everit.json.schema.ValidationException.copy(ValidationException.java:486)
    at org.everit.json.schema.DefaultValidator.performValidation(Validator.java:73)
    at org.everit.json.schema.Schema.validate(Schema.java:152)
    at org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor.process(BaseXacmlJsonRequestPreprocessor.java:199)
    ... 52 common frames omitted
````

# Your code and/or AuthzForce-specific configuration file(s)
In `.../Catalina/localhost/authzforce-ce.xml` the following element should define the location of the JSON request schema used for the JSON request validation.
````
<Environment name="org.ow2.authzforce.domains.xacmlJsonSchemaRelativePath" value="GeoXACML/Request.schema.json" type="java.lang.String" override="false"
                 description="Path to JSON schema file for XACML JSON Profile's Request validation, relative to ${org.ow2.authzforce.config.dir} (if undefined/empty value, the Request.schema.json file from authzforce-ce-xacml-json-model project is used by default)" />
````

**Comment by cdanger** [comment]
Where is the schema file located on the server exactly?

**Comment by securedimensions** [comment]
.../authzforce-ce/conf/GeoXACML/Request.schema.json

**Comment by cdanger** [comment]
Could you attach the full `authzforce-ce.xml` to your first comment?

**Comment by securedimensions** [comment]
# Authzforce Server Version
11.0.1

# authzforce-ce.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Context used by Tomcat -->
<Context path="/authzforce-ce" docBase="/Users/andreasmatheus/Development/GeoXACML3/authzforce-ce-server-11.0.1/webapp">
    <Loader jakartaConverter="TOMCAT" />
	<JarScanner scanClassPath="false">
		<JarScanFilter defaultPluggabilityScan="false" defaultTldScan="false" />
	</JarScanner>

	<!-- Override <context-param>s in web.xml -->
	<Parameter name="logbackConfigLocation" description="Logging configuration file" value="file:/Users/andreasmatheus/Development/GeoXACML3/authzforce-ce-server-11.0.1/conf/logback.xml" override="false" />

	<Parameter name="spring.profiles.active" description="application profiles: '+fastinfoset' to enable FastInfoset support, '-fastinfoset' to disable FastInfoset support" value="-fastinfoset"
		override="false" />

	<!-- <env-entry>s in web.xml do not override entries below iff override=false. -->
	<Environment name="org.ow2.authzforce.config.dir" value="file:/Users/andreasmatheus/Development/GeoXACML3/authzforce-ce-server-11.0.1/conf" type="java.lang.String" override="false"
		description="Configuration directory path that may contain ${...} placeholders, to be resolved as system properties: e.g. ${user.dir}. Default values can be supplied using the ':' separator between key and value (see org.springframework.util.SystemPropertyUtils class)" />

	<Environment name="org.ow2.authzforce.data.dir" value="file:/Users/andreasmatheus/Development/GeoXACML3/authzforce-ce-server-11.0.1/data" type="java.lang.String" override="false"
		description="Data (e.g. data of domains created and managed by the API) directory path that may contain ${...} placeholders, to be resolved as system properties: e.g. ${user.dir}. Default values can be supplied using the ':' separator between key and value (see org.springframework.util.SystemPropertyUtils class)" />

	<Environment name="org.ow2.authzforce.uuid.gen.randomMulticastAddressBased" value="false" type="java.lang.Boolean" override="false"
		description="UUID generator option for domain IDs, set to true if and only if Authzforce deployed in dev environment that is disconnected from the network, i.e. no 'real' Ethernet address to use, set this JNDI variable to 'true' to initialize the UUID (variant 1) generator with a random multicast address instead." />

	<Environment name="org.ow2.authzforce.domains.sync.interval" value="0" type="java.lang.Integer" override="false"
		description="Domains folder-to-memory synchronization interval (seconds); value 0 disables this feature." />

	<Environment name="org.ow2.authzforce.domains.enablePdpOnly" value="false" type="java.lang.Boolean" override="false"
		description="Enable PDP only, i.e. disable all PAP (or other administration) features iff true" />

	<Environment name="org.ow2.authzforce.domains.enableXacmlJsonProfile" value="true" type="java.lang.Boolean" override="false"
		description="Enable support for JSON Profile of XACML 3.0 on domains' PDP endpoints iff true" />

	<Environment name="org.ow2.authzforce.domains.xacmlJsonSchemaRelativePath" value="GeoXACML/Request.schema.json" type="java.lang.String" override="false"
				 description="Path to JSON schema file for XACML JSON Profile's Request validation, relative to ${org.ow2.authzforce.config.dir} (if undefined/empty value, the Request.schema.json file from authzforce-ce-xacml-json-model project is used by default)" />

	<!-- <Environment name="org.ow2.authzforce.webapp.publishedEndpointUrl" value="http://localhost:8080" type="java.lang.String" override="false" description="Base address specified in the auto-generated
		WADL. This parameter allows setting the public URL that may not be the same as the URL the service is deployed on. (For example, the service is behind a proxy of some sort)." /> -->

	<!-- <Environment name="org.ow2.authzforce.webapp.jsonKeysWithArrays" type="java.lang.String" override="false" description="Comma-separated list of JSON keys with values to be always serialized to JSON 
		arrays (even if single-valued). More info: http://cxf.apache.org/docs/jax-rs-data-bindings.html#JAX-RSDataBindings-DealingwithJettisonarrayserializationissues (serializeAsArray always true but no effect 
		if this property undefined or has empty value). The example here works for AuthzForce Manager GUI" value="link,PolicySet,PolicySetIdReference,Policy,PolicyIdReference,Rule,VariableDefinition,AnyOf,AllOf,Match,ObligationExpressions,AdviceExpressions,Obligations,AssociatedAdvice" 
		/> -->

	<Environment name="org.ow2.authzforce.webapp.noNamespaceInJsonOutput" value="false" type="java.lang.Boolean" override="false"
		description="Whether to drop all XML namespaces (JSON key prefixes) from JSON output in XML-to-JSON translation. Enable this for AuthzForce Manager GUI." />

	<Environment name="org.ow2.authzforce.webapp.badReqErrVerbosity" value="10" type="java.lang.Integer" override="false" description="HTTP 400 Bad Request error message verbosity" />
</Context>
```

**Comment by securedimensions** [comment]
# Update
After revisiting this issue, the error is caused by the reference `"$ref": "common-std.schema.json#/definitions/AttributeCategoryType"` because that is loaded from classpath and not from the file system (which does make sense as only `Request.schema.json` is to be loaded from the file system. 

# Fix
After replacing this external reference inline, the `Request.schema.json` located in `...conf/GeoXACML/Request.schema.json` is used properly.
```json
{
	"$schema": "http://json-schema.org/draft-06/schema",
	"$id": "Request.schema.json",
	"title": "JSON schema of Request object defined in JSON profile of GeoXACML 3.0 v1.0",
	"description": "",
	"definitions": {
		"AttributeValueType": {
			"description": "Security warning: this definition allows any JSON object as value. TODO: find a way to validate it somehow. Possible solutions: 1) Modify this schema in production to restrict possible values as much as possible. 2) Any equivalent of XML processContents='strict'. 3) Any JSON processor that enforces a max text length, max number of keys, max object depth.",
			"anyOf": [
				{"type": "boolean"},
				{"type": "number"},
				{"type": "string"},
				{"type": "object"},
				{
					"type": "array",
					"items": {"type": "boolean"},
					"minItems": 0
				},
				{
					"type": "array",
					"items": {
						"type": [
							"string",
							"number"
						]
					},
					"minItems": 0
				},
				{
					"type": "array",
					"items": {"type": "object"},
					"minItems": 0
				}
			]
		},
		"AttributeType": {
			"type": "object",
			"properties": {
				"AttributeId": {
					"type": "string",
					"format": "uri-reference"
				},
				"SRS": {"type": "string"},
				"Issuer": {"type": "string"},
				"IncludeInResult": {"type": "boolean"},
				"DataType": {
					"type": "string",
					"format": "uri-reference"
				},
				"Value": {"$ref": "#/definitions/AttributeValueType"}
			}
		},
		"AttributeCategoryType": {
			"type": "object",
			"properties": {
				"CategoryId": {
					"type": "string",
					"format": "uri-reference"
				},
				"Id": {"type": "string"},
				"Content": {"type": "string"},
				"Attribute": {
					"type": "array",
					"items": {"$ref": "#/definitions/AttributeType"},
					"minItems": 0
				}
			},
			"required": ["CategoryId"],
			"additionalProperties": true
		},
		"RequestReferenceType": {
			"type": "object",
			"properties": {
				"ReferenceId": {
					"type": "array",
					"items": {
						"description": "Each item is a Category/Id",
						"type": "string"
					},
					"minItems": 1
				}
			},
			"required": ["ReferenceId"],
			"additionalProperties": false
		},
		"MultiRequestsType": {
			"type": "object",
			"properties": {
				"RequestReference": {
					"type": "array",
					"items": {"$ref": "#/definitions/RequestReferenceType"},
					"minItems": 1
				}
			},
			"required": ["RequestReference"],
			"additionalProperties": false
		},
		"RequestType": {
			"type": "object",
			"properties": {
				"ReturnPolicyIdList": {"type": "boolean"},
				"CombinedDecision": {"type": "boolean"},
				"XPathVersion": {"type": "string"},
				"Category": {
					"type": "array",
					"items": {"$ref": "#/definitions/AttributeCategoryType"},
					"minItems": 1
				},
				"MultiRequests": {"$ref": "#/definitions/MultiRequestsType"}
			},
			"required": ["Category"],
			"additionalProperties": false
		}
	},
	"type": "object",
	"properties": {
		"Request": {"$ref": "#/definitions/RequestType"}
	},
	"required": ["Request"],
	"additionalProperties": false
}
```

**Comment by securedimensions** [comment]
# Update
There are multiple places where the schema checking takes places

## `org.ow2.authzforce.domains.xacmlJsonSchemaRelativePath`
This class seem to run first and modifications to `authzforce-ce.xml` configuration `<Environment name="org.ow2.authzforce.domains.xacmlJsonSchemaRelativePath" value="Request.schema.json" type="java.lang.String" override="false"
                 description="Path to JSON schema file for XACML JSON Profile's Request validation, relative to ${org.ow2.authzforce.config.dir} (if undefined/empty value, the Request.schema.json file from authzforce-ce-xacml-json-model project is used by default)" />`
seem to affect the processing.

### Isolating the problem
From the `Request.schema.json` file, the external reference `"$ref": "common-std.schema.json#/definitions/AttributeCategoryType"` is used to load the definition for the `AttributeCategoryType`.

The changes for GeoXACML are located in that file `common-std.schema.json`. 
 
Providing the `value="Request.schema.json"` seem to only influence the loading of the main schema file `Request.schema.json` but the `common-std.schema.json` is still loaded from classpath. This results in the response with status code 400:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error><message>#/Request/Category/0/Attribute/0: extraneous key [SRS] is not permitted</message></error>
``` 

Replacing the external reference in `Request.schema.json` with the content from `common-std.schema.json` seem to fix the error:
```xml
{
	"$schema": "http://json-schema.org/draft-06/schema",
	"$id": "Request.schema.json",
	"title": "JSON schema of Request object defined in JSON profile of GeoXACML 3.0 v1.0",
	"description": "",
	"definitions": {
		"AttributeValueType": {
			"description": "Security warning: this definition allows any JSON object as value. TODO: find a way to validate it somehow. Possible solutions: 1) Modify this schema in production to restrict possible values as much as possible. 2) Any equivalent of XML processContents='strict'. 3) Any JSON processor that enforces a max text length, max number of keys, max object depth.",
			"anyOf": [
				{"type": "boolean"},
				{"type": "number"},
				{"type": "string"},
				{"type": "object"},
				{
					"type": "array",
					"items": {"type": "boolean"},
					"minItems": 0
				},
				{
					"type": "array",
					"items": {
						"type": [
							"string",
							"number"
						]
					},
					"minItems": 0
				},
				{
					"type": "array",
					"items": {"type": "object"},
					"minItems": 0
				}
			]
		},
		"AttributeType": {
			"type": "object",
			"properties": {
				"AttributeId": {
					"type": "string",
					"format": "uri-reference"
				},
				"SRS": {"type": "string"},
				"Issuer": {"type": "string"},
				"IncludeInResult": {"type": "boolean"},
				"DataType": {
					"type": "string",
					"format": "uri-reference"
				},
				"Value": {"$ref": "#/definitions/AttributeValueType"}
			}
		},
		"AttributeCategoryType": {
			"type": "object",
			"properties": {
				"CategoryId": {
					"type": "string",
					"format": "uri-reference"
				},
				"Id": {"type": "string"},
				"Content": {"type": "string"},
				"Attribute": {
					"type": "array",
					"items": {"$ref": "#/definitions/AttributeType"},
					"minItems": 0
				}
			},
			"required": ["CategoryId"],
			"additionalProperties": true
		},
		"RequestReferenceType": {
			"type": "object",
			"properties": {
				"ReferenceId": {
					"type": "array",
					"items": {
						"description": "Each item is a Category/Id",
						"type": "string"
					},
					"minItems": 1
				}
			},
			"required": ["ReferenceId"],
			"additionalProperties": false
		},
		"MultiRequestsType": {
			"type": "object",
			"properties": {
				"RequestReference": {
					"type": "array",
					"items": {"$ref": "#/definitions/RequestReferenceType"},
					"minItems": 1
				}
			},
			"required": ["RequestReference"],
			"additionalProperties": false
		},
		"RequestType": {
			"type": "object",
			"properties": {
				"ReturnPolicyIdList": {"type": "boolean"},
				"CombinedDecision": {"type": "boolean"},
				"XPathVersion": {"type": "string"},
				"Category": {
					"type": "array",
					"items": {"$ref": "#/definitions/AttributeCategoryType"},
					"minItems": 1
				},
				"MultiRequests": {"$ref": "#/definitions/MultiRequestsType"}
			},
			"required": ["Category"],
			"additionalProperties": false
		}
	},
	"type": "object",
	"properties": {
		"Request": {"$ref": "#/definitions/RequestType"}
	},
	"required": ["Request"],
	"additionalProperties": false
}
```

## `XacmlJsonUtils`
The second place where the schema is checked is in class `XacmlJsonUtils`. 

### Isolation the problem
The schema loading in `XacmlJsonUtils` is via 
`try (InputStream inputStream = XacmlJsonUtils.class.getResourceAsStream(schemaFilenameRelativeToThisClass))` in line 40. This does not seem to load the `Request.schema.json` from the file system but only from classpath which seem to cause the exception listed in the first comment for this issue.

**Comment by cdanger** [comment]
You should change the names of your JSON schema files to avoid confusion / conflict with the original ones provided in one of Authzforce JARs (therefore on the classpath). This is what we do for testing custom XACML/JSON schema here:
https://github.com/authzforce/server/blob/master/webapp/src/test/suites/json.xml#L63

This unit test works with a custom schema [Request-with-geometry.schema.json](https://github.com/authzforce/server/blob/master/webapp/src/test/resources/authzforce-ce-server/conf) located in the authzforce config directory; and this schema uses the JSON schema file `common-std-with-geometry.schema.json` successfully, as long as it is in the same folder:

```
"$ref": "common-std-with-geometry.schema.json#/definitions/AttributeCategoryType"
```

Please try with way. In other words, do no use the same name `common-std.schema.json` for a custom version of it.

**Comment by securedimensions** [comment]
This is an improvement for loading a custom schema (request + geometry) specified with `org.ow2.authzforce.domains.xacmlJsonSchemaRelativePath`.

This part works fine.

The second part of the issue is not fixed, as class `XacmlJsonUtils` still loads the `Request.schema.json` from the JAR.

But because this issue does not belong here, I am going to close it but will open a dedicated issue in `Authzforce/xacml-json-model`

**Comment by cdanger** [comment]
That's the normal behavior. This XacmlJsonUtils is only for loading the default XACML/JSON schema. It is not used for loading a custom schema (the method is private anyway),but  another class (JsonRiCxfJaxrsProvider), as you can see here:
https://github.com/authzforce/server/blob/master/webapp/src/main/webapp/WEB-INF/beans.xml#L146

So if you put the custom Request schema in authzforce config directory with the other schemas used in refs like for our unit test [here](https://github.com/authzforce/server/blob/master/webapp/src/test/resources/authzforce-ce-server/conf), it sould work, did you try that?
